import {
  FaBootstrap,
  FaCss3Alt,
  FaFigma,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaJs,
  FaNodeJs,
  FaNpm,
  FaPhp,
  FaReact,
  FaVuejs,
} from "react-icons/fa";
import {
  SiExpress,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiXampp,
} from "react-icons/si";


export const skills = [
  {
    id: 1,
    title: "HTML",
    icon: <FaHtml5 />,
    color: "text-orange-500",
    percent: "100%",
  },
  {
    id: 2,
    title: "CSS",
    icon: <FaCss3Alt />,
    color: "text-blue-500",
    percent: "80%",
  },
  {
    id: 3,
    title: "Bootstrap",
    icon: <FaBootstrap />,
    color: "text-purple-500",
    percent: "85%",
  },
  {
    id: 4,
    title: "JavaScript",
    icon: <FaJs />,
    color: "text-yellow-400",
    percent: "70%",
  },
  {
    id: 5,
    title: "React.js",
    icon: <FaReact />,
    color: "text-cyan-400",
    percent: "65%",
  },
  {
    id: 6,
    title: "Tailwind CSS",
    icon: <SiTailwindcss />,
    color: "text-cyan-400",
    percent: "90%",
  },
  {
    id: 7,
    title: "GitHub",
    icon: <FaGithub />,
    color: "text-gray-200",
    percent: "40%",
  },
  {
    id: 8,
    title: "Vue.js",
    icon: <FaVuejs />,
    color: "text-emerald-400",
    percent: "65%",
  },
  {
    id: 9,
    title: "Laravel",
    icon: <SiLaravel />,
    color: "text-red-500",
    percent: "70%",
  },
  {
    id: 10,
    title: "PHP",
    icon: <FaPhp />,
    color: "text-indigo-400",
    percent: "75%",
  },
  {
    id: 11,
    title: "MySQL",
    icon: <SiMysql />,
    color: "text-blue-400",
    percent: "70%",
  },
  {
    id: 12,
    title: "XAMPP",
    icon: <SiXampp />,
    color: "text-orange-500",
    percent: "75%",
  },
  {
    id: 13,
    title: "TypeScript",
    icon: <SiTypescript />,
    color: "text-blue-500",
    percent: "65%",
  },
  {
    id: 14,
    title: "Node.js",
    icon: <FaNodeJs />,
    color: "text-green-500",
    percent: "65%",
  },
  {
    id: 15,
    title: "Express.js",
    icon: <SiExpress />,
    color: "text-gray-300",
    percent: "65%",
  },
  {
    id: 16,
    title: "MongoDB",
    icon: <SiMongodb />,
    color: "text-green-400",
    percent: "60%",
  },
  {
    id: 17,
    title: "Git",
    icon: <FaGitAlt />,
    color: "text-orange-500",
    percent: "70%",
  },
  {
    id: 18,
    title: "Figma",
    icon: <FaFigma />,
    color: "text-pink-400",
    percent: "65%",
  },
  {
    id: 19,
    title: "Vite",
    icon: <SiVite />,
    color: "text-purple-400",
    percent: "75%",
  },
  {
    id: 20,
    title: "npm",
    icon: <FaNpm />,
    color: "text-red-500",
    percent: "75%",
  },
];
